2021-04-20 13:56:04,513 - util.log.mylog - INFO - 进入主页
2021-04-20 13:56:05,819 - util.log.mylog - INFO - 进入国内社区
2021-04-20 13:56:09,083 - util.log.mylog - INFO - 点击舆论管理
2021-04-20 13:56:12,201 - util.log.mylog - INFO - 点击操作
2021-04-20 13:56:16,202 - util.log.mylog - INFO - 点击同意
2021-04-20 13:56:16,213 - util.log.mylog - ERROR - 添加失败
2021-04-20 13:56:16,762 - util.log.mylog - DEBUG - This is a debug log.
Traceback (most recent call last):
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/case/contract.py", line 36, in check
    self.d.Click('xpath','/html/body/div[3]/div/div[3]/button[2]')
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/common/tools.py", line 112, in Click
    self.driver.find_element_by_xpath(value).click()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[3]/div/div[3]/button[2]"}
  (Session info: chrome=89.0.4389.128)

2021-04-20 14:16:59,954 - util.log.mylog - INFO - 进入主页
2021-04-20 14:17:01,300 - util.log.mylog - INFO - 进入国内社区
2021-04-20 14:17:04,552 - util.log.mylog - INFO - 点击舆论管理
2021-04-20 14:17:05,631 - util.log.mylog - INFO - 点击图片审核
2021-04-20 14:17:06,644 - util.log.mylog - ERROR - 测试失败
2021-04-20 14:17:07,310 - util.log.mylog - DEBUG - This is a debug log.
Traceback (most recent call last):
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/case/image_review.py", line 29, in review
    self.d.Click('xpath','//*[@id="app"]/div/div[2]/section/div/section[2]/ul/li[1]/div[2]/div[2]/div[3]/i')
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/common/tools.py", line 112, in Click
    self.driver.find_element_by_xpath(value).click()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="app"]/div/div[2]/section/div/section[2]/ul/li[1]/div[2]/div[2]/div[3]/i"}
  (Session info: chrome=89.0.4389.128)

2021-04-20 14:19:34,973 - util.log.mylog - INFO - 进入主页
2021-04-20 14:19:36,326 - util.log.mylog - INFO - 进入国内社区
2021-04-20 14:19:50,549 - util.log.mylog - INFO - 进入主页
2021-04-20 14:19:51,895 - util.log.mylog - INFO - 进入国内社区
2021-04-20 14:20:04,463 - util.log.mylog - INFO - 进入主页
2021-04-20 14:20:05,801 - util.log.mylog - INFO - 进入国内社区
2021-04-20 14:20:09,020 - util.log.mylog - INFO - 点击舆论管理
2021-04-20 14:20:10,102 - util.log.mylog - INFO - 点击图片审核
2021-04-20 14:20:11,107 - util.log.mylog - INFO - 点击通过
2021-04-20 14:20:11,119 - util.log.mylog - ERROR - 测试失败
2021-04-20 14:20:11,732 - util.log.mylog - DEBUG - This is a debug log.
Traceback (most recent call last):
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/case/image_review.py", line 31, in review
    self.d.WebDriverWait(30, 0.5, '/html/body/div[7]')
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/common/tools.py", line 58, in WebDriverWait
    element = self.driver.find_element(By.XPATH, value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[7]"}
  (Session info: chrome=89.0.4389.128)

2021-04-20 14:23:39,878 - util.log.mylog - INFO - 进入主页
2021-04-20 14:23:41,221 - util.log.mylog - INFO - 进入国内社区
2021-04-20 14:23:44,436 - util.log.mylog - INFO - 点击舆论管理
2021-04-20 14:23:45,505 - util.log.mylog - INFO - 点击图片审核
2021-04-20 14:23:46,520 - util.log.mylog - ERROR - 测试失败
2021-04-20 14:23:47,112 - util.log.mylog - DEBUG - This is a debug log.
Traceback (most recent call last):
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/case/image_review.py", line 29, in review
    self.d.WebDriverWait(30,0.5,'//*[@id="app"]/div/div[2]/section/div/section[2]/ul/li[1]/div[2]/div[2]/div[3]/i')
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/common/tools.py", line 58, in WebDriverWait
    element = self.driver.find_element(By.XPATH, value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="app"]/div/div[2]/section/div/section[2]/ul/li[1]/div[2]/div[2]/div[3]/i"}
  (Session info: chrome=89.0.4389.128)

2021-04-20 14:24:39,503 - util.log.mylog - INFO - 进入主页
2021-04-20 14:24:40,856 - util.log.mylog - INFO - 进入国内社区
2021-04-20 14:24:44,064 - util.log.mylog - INFO - 点击舆论管理
2021-04-20 14:24:45,154 - util.log.mylog - INFO - 点击图片审核
2021-04-20 14:24:46,170 - util.log.mylog - ERROR - 测试失败
2021-04-20 14:24:46,724 - util.log.mylog - DEBUG - This is a debug log.
Traceback (most recent call last):
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/case/image_review.py", line 29, in review
    self.d.WebDriverWait(30,0.5,'//*[@id="app"]/div/div[2]/section/div/section[2]/ul/li[1]/div[2]/div[2]/div[3]/i')
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/common/tools.py", line 58, in WebDriverWait
    element = self.driver.find_element(By.XPATH, value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="app"]/div/div[2]/section/div/section[2]/ul/li[1]/div[2]/div[2]/div[3]/i"}
  (Session info: chrome=89.0.4389.128)

2021-04-20 14:25:21,868 - util.log.mylog - INFO - 进入主页
2021-04-20 14:25:23,207 - util.log.mylog - INFO - 进入国内社区
2021-04-20 14:25:26,463 - util.log.mylog - INFO - 点击舆论管理
2021-04-20 14:25:27,536 - util.log.mylog - INFO - 点击图片审核
2021-04-20 14:25:28,550 - util.log.mylog - ERROR - 测试失败
2021-04-20 14:25:29,107 - util.log.mylog - DEBUG - This is a debug log.
Traceback (most recent call last):
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/case/image_review.py", line 29, in review
    self.d.WebDriverWait(30,0.5,'//*[@id="app"]/div/div[2]/section/div/section[2]/ul/li[1]/div[2]/div[2]/div[3]/i')
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/common/tools.py", line 58, in WebDriverWait
    element = self.driver.find_element(By.XPATH, value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="app"]/div/div[2]/section/div/section[2]/ul/li[1]/div[2]/div[2]/div[3]/i"}
  (Session info: chrome=89.0.4389.128)

2021-04-20 14:25:49,558 - util.log.mylog - INFO - 进入主页
2021-04-20 14:25:50,903 - util.log.mylog - INFO - 进入国内社区
2021-04-20 14:25:54,153 - util.log.mylog - INFO - 点击舆论管理
2021-04-20 14:25:55,216 - util.log.mylog - INFO - 点击图片审核
2021-04-20 14:25:56,232 - util.log.mylog - ERROR - 测试失败
2021-04-20 14:25:56,831 - util.log.mylog - DEBUG - This is a debug log.
Traceback (most recent call last):
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/case/image_review.py", line 29, in review
    self.d.WebDriverWait(30,0.5,'//*[@id="app"]/div/div[2]/section/div/section[2]/ul/li[1]/div[2]/div[2]/div[3]/i')
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/common/tools.py", line 58, in WebDriverWait
    element = self.driver.find_element(By.XPATH, value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="app"]/div/div[2]/section/div/section[2]/ul/li[1]/div[2]/div[2]/div[3]/i"}
  (Session info: chrome=89.0.4389.128)

2021-04-20 14:27:43,870 - util.log.mylog - INFO - 进入主页
2021-04-20 14:27:45,223 - util.log.mylog - INFO - 进入国内社区
2021-04-20 14:27:58,273 - util.log.mylog - INFO - 进入主页
2021-04-20 14:27:59,620 - util.log.mylog - INFO - 进入国内社区
2021-04-20 14:28:02,838 - util.log.mylog - INFO - 点击舆论管理
2021-04-20 14:28:03,906 - util.log.mylog - INFO - 点击图片审核
2021-04-20 14:28:04,922 - util.log.mylog - ERROR - 测试失败
2021-04-20 14:28:05,506 - util.log.mylog - DEBUG - This is a debug log.
Traceback (most recent call last):
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/case/image_review.py", line 29, in review
    self.d.WebDriverWait(30,0.5,'//*[@id="app"]/div/div[2]/section/div/section[2]/ul/li[1]/div[2]/div[2]/div[3]/i')
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/common/tools.py", line 58, in WebDriverWait
    element = self.driver.find_element(By.XPATH, value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="app"]/div/div[2]/section/div/section[2]/ul/li[1]/div[2]/div[2]/div[3]/i"}
  (Session info: chrome=89.0.4389.128)

2021-04-20 14:48:22,401 - util.log.mylog - INFO - 进入主页
2021-04-20 14:48:23,821 - util.log.mylog - INFO - 进入国内社区
2021-04-20 14:48:32,772 - util.log.mylog - INFO - 进入主页
2021-04-20 14:48:34,120 - util.log.mylog - INFO - 进入国内社区
2021-04-20 14:48:37,383 - util.log.mylog - INFO - 进入用户管理
2021-04-20 14:48:38,560 - util.log.mylog - INFO - 进入用户列表
2021-04-20 14:49:31,638 - util.log.mylog - INFO - 进入主页
2021-04-20 14:49:32,994 - util.log.mylog - INFO - 进入国内社区
2021-04-20 14:49:40,907 - util.log.mylog - INFO - 进入主页
2021-04-20 14:49:42,256 - util.log.mylog - INFO - 进入国内社区
2021-04-20 14:49:54,155 - util.log.mylog - INFO - 进入主页
2021-04-20 14:49:55,512 - util.log.mylog - INFO - 进入国内社区
2021-04-20 14:49:58,771 - util.log.mylog - INFO - 进入用户管理
2021-04-20 14:49:59,946 - util.log.mylog - INFO - 进入用户列表
2021-04-20 14:59:02,376 - util.log.mylog - INFO - 进入主页
2021-04-20 14:59:03,722 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:00:14,791 - util.log.mylog - INFO - 进入主页
2021-04-20 15:00:16,140 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:00:19,394 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:00:20,568 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:02:08,198 - util.log.mylog - INFO - 进入主页
2021-04-20 15:02:09,544 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:02:12,808 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:02:13,986 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:04:06,100 - util.log.mylog - INFO - 进入主页
2021-04-20 15:04:07,464 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:04:21,778 - util.log.mylog - INFO - 进入主页
2021-04-20 15:04:23,132 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:04:26,397 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:04:27,567 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:04:43,985 - util.log.mylog - INFO - 进入主页
2021-04-20 15:04:45,331 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:05:12,769 - util.log.mylog - INFO - 进入主页
2021-04-20 15:05:14,117 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:05:17,379 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:05:18,550 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:05:53,397 - util.log.mylog - INFO - 进入主页
2021-04-20 15:05:54,707 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:05:57,963 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:05:59,136 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:07:09,102 - util.log.mylog - INFO - 进入主页
2021-04-20 15:07:10,454 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:07:13,716 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:07:14,895 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:09:34,299 - util.log.mylog - INFO - 进入主页
2021-04-20 15:09:35,664 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:09:38,928 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:09:40,106 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:09:52,904 - util.log.mylog - INFO - 进入主页
2021-04-20 15:09:54,263 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:09:57,524 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:09:58,700 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:10:13,474 - util.log.mylog - INFO - 进入主页
2021-04-20 15:10:14,825 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:10:25,529 - util.log.mylog - INFO - 进入主页
2021-04-20 15:10:26,874 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:11:17,871 - util.log.mylog - INFO - 进入主页
2021-04-20 15:11:19,207 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:11:22,460 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:11:23,630 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:12:31,480 - util.log.mylog - INFO - 进入主页
2021-04-20 15:13:05,485 - util.log.mylog - INFO - 进入主页
2021-04-20 15:13:34,421 - util.log.mylog - INFO - 进入主页
2021-04-20 15:14:06,662 - util.log.mylog - INFO - 进入主页
2021-04-20 15:14:08,012 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:14:16,405 - util.log.mylog - INFO - 进入主页
2021-04-20 15:14:17,747 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:14:20,967 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:14:22,138 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:14:34,547 - util.log.mylog - INFO - 进入主页
2021-04-20 15:14:35,928 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:14:39,148 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:14:40,320 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:15:01,136 - util.log.mylog - INFO - 进入主页
2021-04-20 15:15:02,479 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:15:05,700 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:15:06,874 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:15:19,831 - util.log.mylog - INFO - 进入主页
2021-04-20 15:15:21,190 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:15:24,448 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:15:25,628 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:15:42,255 - util.log.mylog - INFO - 进入主页
2021-04-20 15:15:43,599 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:15:46,859 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:15:48,034 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:16:52,354 - util.log.mylog - INFO - 进入主页
2021-04-20 15:16:53,701 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:16:56,927 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:16:58,105 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:17:14,683 - util.log.mylog - INFO - 进入主页
2021-04-20 15:17:16,037 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:17:26,472 - util.log.mylog - INFO - 进入主页
2021-04-20 15:17:27,817 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:17:31,028 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:17:32,197 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:18:03,042 - util.log.mylog - INFO - 进入主页
2021-04-20 15:18:04,388 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:18:14,045 - util.log.mylog - INFO - 进入主页
2021-04-20 15:18:15,389 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:18:27,911 - util.log.mylog - INFO - 进入主页
2021-04-20 15:18:29,181 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:18:43,142 - util.log.mylog - INFO - 进入主页
2021-04-20 15:18:44,491 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:18:55,288 - util.log.mylog - INFO - 进入主页
2021-04-20 15:18:56,639 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:19:30,952 - util.log.mylog - INFO - 进入主页
2021-04-20 15:19:32,291 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:19:35,509 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:19:36,677 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:20:17,011 - util.log.mylog - INFO - 进入主页
2021-04-20 15:20:18,383 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:20:21,642 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:20:22,819 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:20:47,544 - util.log.mylog - INFO - 进入主页
2021-04-20 15:20:48,925 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:20:52,143 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:20:53,316 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:21:34,488 - util.log.mylog - INFO - 进入主页
2021-04-20 15:21:35,875 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:21:39,085 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:21:40,256 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:21:40,256 - util.log.mylog - INFO - 选择帖子
2021-04-20 15:21:42,272 - util.log.mylog - ERROR - 添加失败
2021-04-20 15:21:42,854 - util.log.mylog - DEBUG - This is a debug log.
Traceback (most recent call last):
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/case/block.py", line 32, in block
    self.d.Click('xpath','//*[@id="el-tooltip-4632"]/div[1]/div[2]/div[1]')
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/common/tools.py", line 112, in Click
    self.driver.find_element_by_xpath(value).click()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="el-tooltip-4632"]/div[1]/div[2]/div[1]"}
  (Session info: chrome=89.0.4389.128)

2021-04-20 15:22:00,697 - util.log.mylog - INFO - 进入主页
2021-04-20 15:22:02,076 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:22:05,294 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:22:06,466 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:22:06,466 - util.log.mylog - INFO - 选择帖子
2021-04-20 15:22:08,480 - util.log.mylog - ERROR - 添加失败
2021-04-20 15:22:09,131 - util.log.mylog - DEBUG - This is a debug log.
Traceback (most recent call last):
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/case/block.py", line 32, in block
    self.d.Click('xpath','//*[@id="el-tooltip-4632"]/div[1]/div[2]/div[1]')
  File "/Users/wangzhipeng/PycharmProjects/UI_automation/common/tools.py", line 112, in Click
    self.driver.find_element_by_xpath(value).click()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="el-tooltip-4632"]/div[1]/div[2]/div[1]"}
  (Session info: chrome=89.0.4389.128)

2021-04-20 15:24:38,710 - util.log.mylog - INFO - 进入主页
2021-04-20 15:24:40,096 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:24:50,723 - util.log.mylog - INFO - 进入主页
2021-04-20 15:24:52,107 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:25:04,480 - util.log.mylog - INFO - 进入主页
2021-04-20 15:25:05,836 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:25:09,042 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:25:10,202 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:25:26,881 - util.log.mylog - INFO - 进入主页
2021-04-20 15:25:28,252 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:25:31,504 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:25:32,671 - util.log.mylog - INFO - 进入用户列表
2021-04-20 15:25:51,849 - util.log.mylog - INFO - 进入主页
2021-04-20 15:25:53,241 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:26:07,966 - util.log.mylog - INFO - 进入主页
2021-04-20 15:26:09,341 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:26:29,927 - util.log.mylog - INFO - 进入主页
2021-04-20 15:26:31,296 - util.log.mylog - INFO - 进入国内社区
2021-04-20 15:26:34,503 - util.log.mylog - INFO - 进入用户管理
2021-04-20 15:26:35,680 - util.log.mylog - INFO - 进入用户列表
